[build]
  command = """
    npm install --prefix landing && npm run build --prefix landing && \
    npm install --prefix application && npm run build --prefix application && \
    rm -rf publish && mkdir -p publish/application && \
    cp -r landing/dist/. publish/ && \
    cp -r application/dist/. publish/application/
  """
  publish = "publish"

  [[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200